# Form implementation generated from reading ui file './ui/index.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Chosen_list = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.Chosen_list.setGeometry(QtCore.QRect(300, 160, 200, 321))
        font = QtGui.QFont()
        font.setKerning(True)
        self.Chosen_list.setFont(font)
        self.Chosen_list.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}")
        self.Chosen_list.setTitle("")
        self.Chosen_list.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Chosen_list.setFlat(False)
        self.Chosen_list.setCheckable(False)
        self.Chosen_list.setObjectName("Chosen_list")
        self.Button_1 = QtWidgets.QPushButton(parent=self.Chosen_list)
        self.Button_1.setGeometry(QtCore.QRect(30, 30, 150, 35))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(15)
        font.setKerning(True)
        self.Button_1.setFont(font)
        self.Button_1.setObjectName("Button_1")
        self.Button_2 = QtWidgets.QPushButton(parent=self.Chosen_list)
        self.Button_2.setGeometry(QtCore.QRect(30, 160, 150, 35))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(15)
        font.setKerning(True)
        self.Button_2.setFont(font)
        self.Button_2.setObjectName("Button_2")
        self.Button_3 = QtWidgets.QPushButton(parent=self.Chosen_list)
        self.Button_3.setGeometry(QtCore.QRect(30, 280, 150, 35))
        font = QtGui.QFont()
        font.setFamily("芫荽")
        font.setPointSize(15)
        font.setKerning(True)
        self.Button_3.setFont(font)
        self.Button_3.setObjectName("Button_3")
        self.Title = QtWidgets.QLabel(parent=self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(150, 0, 500, 150))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.Title.setFont(font)
        self.Title.setStyleSheet("QLabel {\n"
"    color: lightblue;\n"
"}")
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title.setObjectName("Title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuother = QtWidgets.QMenu(parent=self.menubar)
        self.menuother.setObjectName("menuother")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionexit = QtGui.QAction(parent=MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuSettings.addAction(self.actionexit)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuother.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pikachu\'s GUI for Web"))
        self.Button_1.setText(_translate("MainWindow", "X"))
        self.Button_2.setText(_translate("MainWindow", "設定"))
        self.Button_3.setText(_translate("MainWindow", "關閉介面"))
        self.Title.setText(_translate("MainWindow", "Pikachu\' s House"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuother.setTitle(_translate("MainWindow", "other"))
        self.actionexit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
